### ISSUE TITLE
Remove naming restrictions and .notebook and .note requirements.

### ISSUE THREAD

**Issue by patleeman** [Collateapp/collate-file-format#2]
I'm opening up a discussion here to discuss changing the naming convention for notebooks and notes.

Currently all items located within the note format must be named with alphanumeric characters and hyphens.  i.e. `this-is-a-notebook-1.notebook` or `this-is-a-note.note` which is much more difficult to read in plain text.

The current file structure:

This seems overly cautious and unnecessary.  I think that the restriction should be removed, and that any directory located under the Collection (1st child) should be interpreted as a notebook, and any directory nested under a notebook (2nd child) should be interpreted as a note.

Old structure
```
Collection
|-- Inbox-for-my-stuff.notebook
|   `-- Welcome-to-the-jungle.note
|       |-- Welcome-to-the-jungle.md
|       `-- attachments
|           `-- attachment.jpg
```

New structure
```
Collection
|-- Inbox for my stuff
|   `-- Welcome to the jungle
|       |-- Welcome to the jungle.md
|       `-- attachments
|           `-- attachment.jpg
```

This doesn't allow for nested notebooks or nested notes however as notebooks and notes are inferred from their location within the tree structure.

I'm going to leave this open for a while for discussion.

**Comment by youngheart80** [comment]
Personally, I have little use for "nested" notebooks of the stack style that Evernote employed, so modifying the format that way wouldn't be a downer for me. But if I remember correctly, OneNote uses the idea of nesting book rather extensively, so if there were users coming from that world (not super likely at this point, I know), but they might miss such abilities.

As it stands right now, the naming conventions don't really affect me either way, but thought I'd add something to the discussion.

**Comment by patleeman** [comment]
Thanks for your input!

I'm going to go ahead and remove the strict naming convention with the `.notebook` or `.note` suffixes. The title input into the note or notebook will be the file names.

**Comment by patleeman** [comment]
Re-reading the original post, i realized I was pretty unclear.

I just want to change

`this-is-a-notebook-1.notebook`

to 

`this is a notebook 1/`

**Comment by patleeman** [comment]
The naming convention has been removed.
